[package]
name = "unc-ai-surveillance-system-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.21.0"
actix-web = "4"
serde = "1.0"
serde_yaml = "0.9"